### ISSUE TITLE
Storage file size limitation

### ISSUE THREAD

**Issue by alanlanglois** [psperber/redux-persist-electron-storage#1]
I was wondering if some kind of size limitation exists using electron storage. 
I'm facing an issue using AsyncStorage, and electron storage might fix it. 
How data are stored and is there a limitation using it to save and restore the states of my app?

**Comment by psperber** [comment]
electron-store is using a simple textfile for holding the data, so you IO should be the only limitation.
But keep in mind: AsyncStorage is for react-native, isn't it? electron-storage is only working in electron application, therefore i guess it won't fit your requirements.
