### ISSUE TITLE
Clear storage

### ISSUE THREAD

**Issue by loopmode** [psperber/redux-persist-electron-storage#10]
Hi. The module doesn't export a function to clear the storage. How would I go about to implement a "clear" button in my app?

I guess either we could expose the store instance "reset" method.. or should one simply locate the file on the filesystem and delete it?

**Comment by JasonBristol** [comment]
Not sure the design philosophy of redux-persist (just started using it), but it feels a bit weird to me to modify the persisted state directly.

I'd imagine a better approach would be to clear your state organically via a redux action and the next time your state is persisted it should represent a cleared state.

**Comment by loopmode** [comment]
I guess currently, the idea is to "simply" reset the store state, implicitly clearing the persisted state as well, right?

**Comment by psperber** [comment]
Yes, I think the best way would be to feed the initial state to you redux store. I am not sure, if editing the electron store directly can cause more issue then it solves. I will think about it.
