### ISSUE TITLE
README is wrong or outdated

### ISSUE THREAD

**Issue by phbernard** [psperber/redux-persist-electron-storage#2]
Thank you for this module!

Currently, the README asks to:

  - Follow [redux-persist installation procedure](https://github.com/rt2zz/redux-persist#redux-persist)
  - Update the call to `persistStore` by calling `createElectronStorage`

When doing so, the app prints an error message in the console:

    redux-persist: invalid option passed to persistStore: "storage". You may be incorrectly passing persistConfig into persistStore, whereas it should be passed into persistReducer.

The message is relevant, since the installation procedure of redux-persist actually creates a storage object and passes it to `persistReducer`, as advised in the error message. And the error is real: the file is not stored in `app.getPath('userData')`.

So the README is currently wrong. I suppose this is due to a change in redux-persist, hence the very specific error message.

A simple update of the README file would do the trick. If that's okay, I can submit a PR. Just let me know.

**Comment by psperber** [comment]
Of course, feel free to submit a PR :) Thank you!

**Comment by phbernard** [comment]
It's https://github.com/psperber/redux-persist-electron-storage/pull/3 :)
